builds:
  - goos: [linux, windows]
    goarch: [386, amd64, arm64]
    ldflags:
      - -s -w -X main.GitSha={{.ShortCommit}} -X main.GitBranch=master -X main.GitTag={{.Version}}
archives:
  - wrap_in_directory: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  use: git
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^style:'
    - '^ci:'

release:
  draft: true

nfpms:
- file_name_template: "{{ .ConventionalFileName }}"
  vendor: Alterway
  maintainer: security@alterway.fr
  license: Apache 2.0
  homepage: https://github.com/alterway/sshportal
  description: |-
      Transparent SSH bastion written in Go

  formats:
    - deb
    - rpm

  dependencies:
    - systemd
    - libnss-systemd

  recommends:
    - sqlite3

  suggests:
    - mariadb

  provides:
    - sshportal

  priority: optional

  bindir: /usr/bin

  contents:
    - src: packaging/etc/
      dst: /etc/
      type: tree
    - src: packaging/selinux/sshportal.pp
      dst: /usr/share/selinux/packages/sshportal.pp

  scripts:
    preinstall: "packaging/preinstall.sh"
    postinstall: "packaging/postinstall.sh"
    postremove: "packaging/postremove.sh"

  deb:
    scripts:
      templates: packaging/deb/template